### ISSUE TITLE
compile error while installing

### ISSUE THREAD

**Issue by firex2** [hobbyquaker/mqtt-scripts#1]
i tried to install mqtt-scripts in Docker-containers (tried Ubuntu and Alpine Linux) and i get two errors. The gyp module tries to compile "bufferutil" and "utf-8-validate". Here the error message from Ubuntu Docker phusion/baseimage:

```
root@fa20b76cee76:/# npm install -g mqtt-scripts

> bufferutil@1.1.0 install /usr/local/lib/node_modules/mqtt-scripts/node_modules/bufferutil
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mqtt-scripts/node_modules/bufferutil
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.1.0 Exit status 1

> utf-8-validate@1.1.0 install /usr/local/lib/node_modules/mqtt-scripts/node_modules/utf-8-validate
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-52-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mqtt-scripts/node_modules/utf-8-validate
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
/usr/local/lib
└── mqtt-scripts@0.10.2
```

the error in Alpine Linux looks different, tell me if you want to see it :)

**Comment by hobbyquaker** [comment]
I guess this is a problem with the naming of the Nodejs executable under Ubuntu (iirc it is called `nodejs` and not `node`). I'd try to either symlink that to /usr/local/bin/node or to install Node not from the Ubuntu repos but via [n](https://github.com/tj/n).

**Comment by hobbyquaker** [comment]
Here is a simple example of a Dockerfile using `n` to install the latest stable Node.js:
```
FROM ubuntu:trusty

RUN apt-get update && apt-get install -y git make build-essential curl

WORKDIR /usr/local/src/n
RUN git clone https://github.com/tj/n . && \
    make install && n stable
```

**Comment by firex2** [comment]
hi, it doesnt change with a node version installed with n:

```
npm install -g mqtt-scripts

> bufferutil@1.1.0 install /root/n/lib/node_modules/mqtt-scripts/node_modules/bufferutil
> node-gyp rebuild

sh: 1: node-gyp: Permission denied

> utf-8-validate@1.1.0 install /root/n/lib/node_modules/mqtt-scripts/node_modules/utf-8-validate
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
/root/n/lib
└── mqtt-scripts@0.10.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.1.0 (node_modules/mqtt-scripts/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.1.0 (node_modules/mqtt-scripts/node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
```

**Comment by hobbyquaker** [comment]
It did change :)
Your first try lead to `/bin/sh: 1: node: not found` - now you got `sh: 1: node-gyp: Permission denied` 
Can you please paste your Dockerfile and any additional steps you did?

**Comment by hobbyquaker** [comment]
I just did a little test and created this Dockerfile:
```
FROM ubuntu:trusty

MAINTAINER Sebastian Raff https://github.com/hobbyquaker

RUN apt-get update && apt-get install -y git make build-essential curl

WORKDIR /usr/local/src/n
RUN git clone https://github.com/tj/n . && \
    make install && n 6.9 
RUN npm install -g mqtt-scripts
RUN mkdir -p /opt/mqtt-scripts

VOLUME ["/opt/mqtt-scripts"]

WORKDIR /root

ENTRYPOINT ["/usr/local/lib/node_modules/mqtt-scripts/index.js"]
CMD ["-v", "debug", "-d", "/opt/mqtt-scripts"]
```

This seems to work.

**Comment by firex2** [comment]
basically i do the same, except:
- installing n via "curl -L https://git.io/n-install | bash"
- my baseimage for my docker is "phusion/baseimage:latest"
until now, i used phusion/baseimage or a alpine-s6 for all my dockers, even your hue2mqtt :)
