### ISSUE TITLE
TypeError('Parameter "url" must be a string)

### ISSUE THREAD

**Issue by nanosonde** [hobbyquaker/mqtt-scripts#3]
```
pi@rpi3-knx:~/mqtt-scripts $ node index.js -vdebug
2018-08-11 14:29:01.765 <info>  mqtt-scripts 1.1.0 starting
url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not boolean
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at Object.connect (/home/pi/mqtt-scripts/node_modules/mqtt/lib/connect/index.js:56:22)
    at Object.<anonymous> (/home/pi/mqtt-scripts/index.js:119:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Comment by hobbyquaker** [comment]
You have to set your MQTT Broker URL via the `--url` parameter, e.g. `--url mqtt://broker-address` or with auth and tls `--url mqtts://user:pass@broker-adress:broker-port`

**Comment by nanosonde** [comment]
Yes, that's clear. :-)
However, I saw that a default URL for localhost is provided and it seemed that it wasn't used for some reason. I think it is related to yargs.

I will close this for now.

**Comment by hobbyquaker** [comment]
Oh, sure, you're right. Has to be fixed :-)

**Comment by hobbyquaker** [comment]
It works when you use a space between `-v` and `debug`.
